### ISSUE TITLE
Refonte du composant Tooltip

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#1430]
# Tooltip

## Idée de syntaxe

```js
<Tooltip>
  <Tooltip.Trigger>
    <Button />
  </Tooltip.Trigger>

  <Tooltip.Content>
    Contenu de ma tooltip
  </Tooltip.Content>
</Tooltip>
```

## TODO

- [ ] Trouver un nom
- [ ] Créer le composant
- [ ] Positionnement simple de la tooltip
- [ ] Trigger events
- [ ] Calcul pour positionner la tooltip à la moitié de l'élément `<Tooltip.Trigger>`
- [ ] Calcul de la place disponible dans l'écran pour activer le mode 100%.
