### ISSUE TITLE
Kitten V3

### ISSUE THREAD

**Issue by FlorentD** [KissKissBankBank/kitten#1876]
## Évolutions proposées :

- [ ] Ajout d'un CSS Reset (basé sur le CSS Reset de Eric Meyer, avec des reset spécifiques pour les soulignements de liens et les boutons) _proposé par @joachimesque et @Morgan-jarry_
- [x] Suppression de l'app Styleguide et des composants Karl #2175 
- [ ] Évolution de la gestion des couleurs #1670
- [x] Mise à jour et check de toutes nos dépendances
- [x] `TextInput` et `Button` : déprécation des props de taille, et remplacement par une prop `size` ([discussion](https://kisskiss.slack.com/archives/G1ZHFLS3E/p1604910696004800)) #2315
- [x] Mise à jour de tous les composants `Button`, unification de `buttons/button` et `buttons/button/button` #2170 + #2315
- [ ] Réflexion à mener sur le rangement des composants et nommage des catégories (Atomic design)

### Composants Legacy à supprimer

Ces composants sont dans cette liste parce que :

1. ils sont encore en SASS et n'ont jamais été migrés en CSS-in-JS
2. ils ne sont pas utilisés sur les apps KissKissBankBank ou Lendopolis

On considère donc qu'ils ne valent pas la peine d'être migrés, et peuvent être supprimés.

- [x] Déprécation, ou suppression de l'ancien header et des composants associés inutilisés (menu, dropdown, etc) #2322
- [x] Supprimer le style de `k_Alert` #2355
- [x] Supprimer l'utilitaire `blockAlign`, déprécié et remplacé par `alignSelf` (#2291)  #2321
- [x] `buttons/button-image-with-text`
- [x] `buttons/button-image-with-text-and-badge`
- [x] `cards/article-card` #2312
- [x] `cards/contribution-card` #2312
- [x] `cards/crowdfunding-card/widget` #2312 (https://github.com/KissKissBankBank/kisskissbankbank/pull/10046/files#r558220125)
- [x] `cards/project-card` #2312
- [x] `cards/project-creator-card` #2312
- [x] `cards/project-similar-card` #2312
- [x] `cards/reward-card/legacy` #2312
- [x] `cards/similar-projects-card` #2312
- [x] `carousel/tab-bar-carousel` #2367
- [x] `dropdowns/dropdown` #2322
- [x] `dropdowns/phone-dropdown` #2322
- [x] `dropdowns/user-menu` #2322
- [x] `form/form-amount-and-currency` (à vérifier)
- [x] `form/form-row` #2335
- [x] `form/search` #2338
- [x] `form/select-with-state` (une fois DropdownSelect poussé)
- [x] `form/slider`  #2325
- [x] `grid/lego-grid` #2323
- [x] `icons/arrow-icon[deprecated]` #2313
- [x] `images/image-with-caption` #2366
- [x] `links/external-rich-link` #2365
- [x] `lists/nav-list` #2322
- [x] `lists/tag-list` #2363
- [x] `popovers/call-to-action-popover.js` #2362
- [x] `popovers/popover.js` #2362
- [x] `simulators` ([supprimé de Lendo](https://github.com/KissKissBankBank/kkbb-lendopolis-clients/pull/1428#pullrequestreview-515470537))  #2325
- [x] `sliders/slider-bar.js`  #2325
- [x] `sliders/slider-tooltip.js`  #2325
- [x] `sliders/slider-wit-tooltip-and-power.js` ([supprimé de Lendo](https://github.com/KissKissBankBank/kkbb-lendopolis-clients/pull/1428#pullrequestreview-515470537))  #2325
- [x] `tooltips/question-mark-with-tooltip` #2375
- [x] `tooltip/static-tooltip` #2375
- [x] `tooltip/tooltip` #2375
- [x] `tooltip/tooltip-new` #2375
- [x] `tours/header-tour` #2356
- [x] `tours/tour` #2356
- [x] `tours/tour-popover` #2356
- [x] `tours/tour-step` #2356
- [x] `uploaders/simple-uploader` #2361
- [x] `uploaders/uploader` #2361

#### Kitten

- [x] `typography/paragraph` #2382 

#### KissKiss

- [x] `box/link-box/link-box/deprecated.js` https://github.com/KissKissBankBank/kisskissbankbank/pull/10153
- [x] `buttons/button` https://github.com/KissKissBankBank/kisskissbankbank/pull/10163
- [x] `comments/comment` && `form/comment` #2368
- [x] `comments/comment-form` && `form/comment-form` #2368
- [x] `comments/comment-avatar` && `form/comment-avatar` #2368
- [x] `form/switch` -> `kiss/modules/cart/components/anonymous-contribution`
- [x] `headers/header` #2369
- [x] `headers/header-logo` #2369
- [x] `headers/header-titles` #2369
- [x] `loaders/*` (déplacement vers `atoms/loader` et `atoms/loader-with-paragraph`) #2371
- [x] `navigation/horizontal-nav` à remplacer par `NavBar` #2048
- [x] `navigation/tab-bar` à remplacer par `NavBar` #2048
- [x] `notifications/badge.js`
- [x] `tooltip/tooltip` https://github.com/KissKissBankBank/kisskissbankbank/pull/10170
- [x] `typography/paragraph` https://github.com/KissKissBankBank/kisskissbankbank/pull/10190

#### Lendo

- [ ] `buttons/button`
- [ ] `form/switch` ???
- [x] `headers/header` #2369
- [x] `headers/header-logo` #2369
- [ ] `loaders/*` (déplacement vers `atoms/loader` et `atoms/loader-with-paragraph`) #2371
- [x] `navigation/horizontal-nav` à remplacer par `NavBar` #2048
- [x] `navigation/tab-bar` à remplacer par `NavBar` #2048
- [ ] `tooltip/tooltip` (4 occurences)
- [ ] `typography/paragraph`

## Composants SCSS à convertir en CSS-in-JS

- [x] `avatar/avatar-with-text-and-badge` (#2344 pour la partie badge, refacto complexe à faire en plus)
- [x] `box/information-box`
- [x] `buttons/button-icon` #2170
- [x] `buttons/button-image` #2170
- [x] `buttons/button-question-mark-icon` #2170
- [x] `buttons/close-button` #2170
- [x] `buttons/social-button-icon` #2170
- [x] `buttons/social-button-icon-words` #2170
- [x] `cards/simple-card`
- [x] `dropdowns/dropdown-button`
- [x] `dropdowns/v2`
- [x] `form/form-actions`
- [x] `form/label` #2345
- [x] `form/location-input` (Utilisation de DropDown ?) ajout du style `orion`
- [x] `form/switch` #2346 -> remplacé par `toggle-switch`
- [x] `form/text-input-and-select` (à vérifier)
- [x] `grid/grid`
- [x] `grid/row` (utilité à confirmer)
- [x] `grid/side-grid` #2379
- [x] `images/image-cropper` #2373
- [x] `layout/line`
- [x] `layout/marger`
- [x] `layout/responsive-iframe-container`
- [x] `layout/separator`
- [x] `layout/side-layout` #2379
- [x] `layout/vertical-stroke`
- [x] `links/link-list` #2339 
- [x] `loaders/loader` #2347
- [x] `loaders/loader-with-paragraph` #2347
- [x] `menus/header-menu/components/badge.js` (inspection minutieuse à effectuer sur l'utilisation) #2344
- [x] `navigation/header-nav`  #2343
- [x] `notifications/badge.js` #2344
- [x] `notifications/icon-badge.js` #2344
- [x] `steppers/stepper.js`
- [x] `steppers/stepper-icon`
- [x] `typography/title` #2359
- [x] `typography/paragraph`#2358
- [x] `typography/sup-title` #2353
- [x] `typography/text` #2341

### A intégrer dans le build esm

- [x] `parseHtml` #2372 

### Plus de réflexion nécessaire

- [x] `dev`
  - Delete #2326
  - Migrate #2329
  Est-ce qu'on supprime `DevGrid`, ou est-ce qu'on le modernise pour usage dans l'app KissKiss ?

## Super cool :

- [x] KITTEN SUR VERCEL

## Propositions pour Kitten V4

- [ ] Création d'un theming (Custom properties ? Themes StyledComponent ?) #2244

**Comment by joachimesque** [comment]
Voilà les composants selon qu'ils sont dans Styled Components ou dans SASS

- ✅ Composants entièrement stylés dans Styled Components (85)
- ❌ Composants entièrement ou en partie stylés dans `SASS` (79)
- 🔸 Composants qui n’ont pas de styles à eux (20)

```
.
├── accessibility
│   └── visually-hidden ✅
├── accordeon ✅
├── avatar
│   └── avatar-with-text-and-badge ❌
├── box
│   ├── doc-link-box 🔸
│   ├── information-box ❌
│   └── link-box ✅
│       └── link-box/deprecated.js ❌
├── buttons
│   ├── button
│   │   ├── button ✅
│   │   ├── button/deprecated ❌
│   │   └── helpers
│   ├── button-group ✅
│   ├── button-icon ❌
│   ├── button-image ❌
│   ├── button-image-with-text ❌
│   ├── button-image-with-text-and-badge ❌
│   ├── button-question-mark-icon ❌
│   ├── checkable-button ✅
│   ├── close-button ❌
│   ├── social-button-icon ❌
│   ├── social-button-icon-words ❌
│   └── tag-button ✅
├── cards
│   ├── article-card 🔸
│   ├── backer-card ✅
│   ├── cart-reward-card ✅
│   ├── clickable-card ✅
│   ├── contribution-card 🔸
│   ├── crowdfunding-card ✅
│   │   ├── stories
│   │   └── widget
│   ├── donation-card ✅
│   ├── engagement-card ✅
│   │   └── withImage ✅
│   ├── project-card ❌
│   ├── project-creator-card ❌
│   ├── project-similar-card ❌
│   ├── reward-card ✅
│   │   └── legacy ✅
│   ├── reward-edition ✅
│   ├── similar-projects-card 🔸
│   ├── simple-card ❌
│   ├── team-card ✅
│   ├── triptych ✅
│   ├── vertical-card ✅
│   └── vertical-card-with-action ✅
├── carousel
│   ├── carousel ✅
│   ├── nav-tab-carousel ✅
│   ├── simple-carousel ✅
│   └── tab-bar-carousel 🔸
├── comments
│   ├── comment ✅
│   ├── comment-avatar ✅
│   └── comment-form ✅
├── date-picker ✅
│   └── standalone-range ✅
├── details ✅
├── dev ❌
├── dropdowns
│   ├── dropdown ❌
│   ├── dropdown-button ❌
│   ├── phone-dropdown ❌
│   ├── user-menu 🔸
│   └── v2 ❌
├── expandable
│   └── expand-board ✅
├── form
│   ├── autocomplete ✅
│   ├── checkbox ❌
│   ├── checkbox-set ❌
│   ├── comment 🔸
│   ├── comment-avatar 🔸
│   ├── comment-form 🔸
│   ├── field 🔸
│   ├── form-actions ❌
│   ├── form-amount-and-currency 🔸
│   ├── form-phone-number 🔸
│   ├── form-row ❌
│   ├── label ❌
│   ├── location-input ❌
│   ├── password-input ✅
│   ├── pill-number-input ✅
│   ├── radio-button ❌
│   ├── radio-button-set ❌
│   ├── rich-text-input 🔸
│   ├── search ❌
│   ├── select-with-state ❌
│   ├── slider ❌
│   ├── switch ❌
│   ├── text-input ✅
│   ├── text-input-and-select ❌
│   ├── text-input-with-button ✅
│   ├── text-input-with-icon ✅
│   ├── text-input-with-limit ✅
│   ├── text-input-with-unit ✅
│   ├── text-input-with-unit-form ✅
│   └── toggle-switch ✅
├── grid
│   ├── adaptable-grid ✅
│   ├── container ✅
│   ├── grid ❌
│   ├── lego-grid ❌
│   ├── row ❌
│   ├── scrollable-container ✅
│   ├── side-grid ❌
│   └── sticky-container ✅
├── headers
│   ├── header ❌
│   ├── header-logo ❌
│   └── header-titles ❌
├── heroes
│   └── hero ✅
├── icons 🔸
├── illustrations 🔸
├── images
│   ├── image-cropper ❌
│   └── image-with-caption ❌
├── layout
│   ├── arrow-container ✅
│   ├── horizontal-stroke ✅
│   │   └── common
│   ├── icon-container ✅
│   ├── line ❌
│   ├── marger ❌
│   ├── responsive-iframe-container ❌
│   ├── separator ❌
│   ├── side-layout ❌
│   └── vertical-stroke ❌
├── lines
│   └── info-lines ✅
├── links
│   ├── external-rich-link ❌
│   └── link-list ❌
├── lists
│   ├── bullet-list ✅
│   ├── check-list ✅
│   ├── icon-list ✅
│   ├── list ✅
│   ├── nav-list ✅
│   ├── tag-list ❌
│   └── timeline ✅
├── loaders
│   ├── loader ❌
│   └── loader-with-paragraph ❌
├── logos
│   ├── kisskissbankbanklogo 🔸
│   └── lendopolis-logo 🔸
├── media 🔸
├── menus
│   └── header-menu ✅
│       └── components/badge.js ❌
├── meters
│   ├── counter-block ✅
│   ├── progress ✅
│   └── progress-ring ✅
├── modals
│   ├── modal ✅
│   ├── next ✅
│   └── overlay ✅
├── navigation
│   ├── header-nav ✅
│   ├── horizontal-nav ❌
│   ├── nav-bar ✅
│   ├── pagination ✅
│   └── tab-bar ❌
├── notifications
│   ├── alert.js ✅
│   ├── badge.js ❌
│   └── icon-badge.js ❌
├── pages
│   └── markdown 🔸
├── popovers
│   ├── call-to-action-popover.js ❌
│   ├── popover.js ❌
│   └── simple-popover ✅
├── search
│   └── search-input ✅
├── simulators ❌
├── sliders
│   ├── slider-bar.js ❌
│   ├── slider-tooltip.js ❌
│   └── slider-with-tooltip-and-power.js ❌
├── status-with-bullet ✅
├── steppers
│   ├── next
│   │   └── stepper ✅
│   ├── stepper.js ❌
│   ├── stepper-icon.js ❌
│   └── vertical-stepper ✅
├── tables
│   ├── double-entry-table ✅
│   ├── list-table ✅
│   └── single-entry-table ✅
├── text-copy ✅
├── tooltips
│   ├── question-mark-with-tooltip 🔸
│   ├── static-tooltip ❌
│   ├── tooltip ❌
│   └── tooltip-new ❌
├── tours
│   ├── header-tour ❌
│   ├── highlight-halo ✅
│   ├── tour ❌
│   ├── tour-popover ❌
│   └── tour-step ❌
├── typography
│   ├── paragraph ❌
│   │   └── next ✅
│   ├── sup-title ❌
│   ├── text ❌
│   ├── title ✅
│   └── title-with-stroke ✅
├── uploaders
│   ├── basic-uploader ✅
│   ├── document-manager ✅
│   ├── simple-uploader ❌
│   └── uploader ❌
└── videos
    ├── embed-player ✅
    ├── gif-video ✅
    └── video ✅
```

**Comment by joachimesque** [comment]
Arbre des composants un peu amélioré :

✅ Ready dans React
❌ VIEUX
🐱 Utilisé dans d'autres composants Kitten
🖤 Utilisé activement chez KissKiss
🏬 Utilisé activeemnt chez LendoPOILS
🔥 Ça on devrait pouvoir brûler

```
.
├── accessibility                                          
│   └── visually-hidden                     ✅🐱 🖤 🏬     
├── accordeon                               ✅🐱 🖤        
├── avatar
│   └── avatar-with-text-and-badge          ❌🐱 🖤 🏬     
├── box
│   ├── doc-link-box                        🔸🐱    🏬     
│   ├── information-box                     ❌🐱 🖤        
│   └── link-box                            ✅      🏬     
│       └── link-box/deprecated.js          ❌   🖤        
├── buttons
│   ├── button
│   │   ├── button                          ✅🐱 🖤 🏬     
│   │   ├── button/deprecated               ❌🐱 🖤 🏬     
│   │   └── helpers
│   ├── button-group                        ✅🐱 🖤        
│   ├── button-icon                         ❌🐱 🖤 🏬     
│   ├── button-image                        ❌🐱 🖤 🏬     
│   ├── button-image-with-text              ❌           🔥
│   ├── button-image-with-text-and-badge    ❌           ?? Kitten dans dropdowns/user-menu,
│   │                                                       KissKiss à supprimer de app-kitten
│   ├── button-question-mark-icon           ❌🐱 🖤        
│   ├── checkable-button                    ✅      🏬     
│   ├── close-button                        ❌🐱 🖤        
│   ├── social-button-icon                  ❌   🖤 🏬     
│   ├── social-button-icon-words            ❌   🖤        
│   └── tag-button                          ✅🐱 🖤 🏬     
├── cards
│   ├── article-card                        🔸           🔥
│   ├── backer-card                         ✅   🖤        
│   ├── cart-reward-card                    ✅   🖤        
│   ├── clickable-card                      ✅             
│   ├── contribution-card                   🔸           🔥
│   ├── crowdfunding-card                   ✅🐱 🖤 🏬     
│   │   ├── stories
│   │   └── widget                          ✅   🖤        
│   ├── donation-card                       ✅   🖤        
│   ├── engagement-card                     ✅🐱 🖤        
│   │   └── withImage                       ✅🐱 🖤        
│   ├── project-card                        ❌🐱         🔥 Kitten Utilisé dans Karl
│   ├── project-creator-card                ❌           🔥
│   ├── project-similar-card                ❌🐱         🔥 Kitten Utilisé dans Karl
│   ├── reward-card                         ✅🐱 🖤        
│   │   └── legacy                          ✅           🔥 Après vérification sur KissKiss
│   ├── reward-edition                      ✅   🖤        
│   ├── similar-projects-card               🔸           🔥
│   ├── simple-card                         ❌🐱 🖤 🏬     
│   ├── team-card                           ✅      🏬     
│   ├── triptych                            ✅🐱 🖤        
│   ├── vertical-card                       ✅🐱    🏬     
│   └── vertical-card-with-action           ✅🐱           
├── carousel
│   ├── carousel                            ✅🐱 🖤 🏬     
│   ├── nav-tab-carousel                    ✅   🖤 🏬     
│   ├── simple-carousel                     ✅🐱 🖤        
│   └── tab-bar-carousel                    🔸           🔥
├── comments
│   ├── comment                             ✅   🖤      !! KissKiss migrer les versions dépréciées
│   ├── comment-avatar                      ✅🐱           
│   └── comment-form                        ✅   🖤      !! KissKiss migrer les versions dépréciées
├── date-picker                             ✅             
│   └── standalone-range                    ✅             
├── details                                 ✅   🖤        
├── dev                                     ❌   🖤 🏬     
├── dropdowns
│   ├── dropdown                            ❌🐱    🏬   ?? Lendo utilisé pour le rendu statique
│   ├── dropdown-button                     ❌🐱         ?? Lendo utilisé pour le rendu statique
│   ├── phone-dropdown                      ❌      🏬   ?? Lendo utilisé pour le rendu statique
│   ├── user-menu                           🔸      🏬   ?? Lendo utilisé pour le rendu statique
│   └── v2                                  ❌🐱           
├── expandable
│   └── expand-board                        ✅🐱 🖤        
├── form
│   ├── autocomplete                        ✅🐱 🖤      ?? après maker
│   ├── checkbox                            ❌🐱 🖤 🏬     
│   ├── checkbox-set                        ❌           !! en cours d'amélioration
│   ├── comment                             🔸   🖤      !! déprécié, voir comments/comment
│   ├── comment-avatar                      🔸           !! déprécié, voir comments/comment
│   ├── comment-form                        🔸   🖤      !! déprécié, voir comments/comment
│   ├── field                               🔸🐱 🖤 🏬     
│   ├── form-actions                        ❌🐱 🖤 🏬     
│   ├── form-amount-and-currency            🔸           🔥
│   ├── form-phone-number                   🔸      🏬     
│   ├── form-row                            ❌🐱         🔥 Kitten Utilisé dans Karl
│   ├── label                               ❌🐱 🖤 🏬     
│   ├── location-input                      ❌   🖤        
│   ├── password-input                      ✅🐱 🖤        
│   ├── pill-number-input                   ✅             
│   ├── radio-button                        ❌🐱 🖤 🏬     
│   ├── radio-button-set                    ❌🐱           
│   ├── rich-text-input                     🔸           🔥
│   ├── search                              ❌           🔥
│   ├── select-with-state                   ❌🐱           
│   ├── slider                              ❌🐱         ?? Kitten utilisé dans image cropper
│   ├── switch                              ❌   🖤        
│   ├── text-input                          ✅🐱 🖤 🏬     
│   ├── text-input-and-select               ❌🐱         ?? Kitten utilisé dans form-phone-number,
│   │                                                       form-amount-and-currency
│   ├── text-input-with-button              ✅   🖤 🏬     
│   ├── text-input-with-icon                ✅   🖤        
│   ├── text-input-with-limit               ✅🐱           
│   ├── text-input-with-unit                ✅🐱    🏬     
│   ├── text-input-with-unit-form           ✅🐱           
│   └── toggle-switch                       ✅🐱 🖤 🏬     
├── grid
│   ├── adaptable-grid                      ✅   🖤        
│   ├── container                           ✅🐱 🖤 🏬     
│   ├── grid                                ❌🐱 🖤 🏬     
│   ├── lego-grid                           ❌🐱         🔥 Kitten utilisé dans Karl
│   ├── row                                 ❌🐱         🔥 Kitten utilisé dans Karl
│   ├── scrollable-container                ✅🐱 🖤 🏬     
│   ├── side-grid                           ❌      🏬     
│   └── sticky-container                    ✅🐱           
├── headers
│   ├── header                              ❌🐱 🖤 🏬     
│   ├── header-logo                         ❌🐱 🖤 🏬     
│   └── header-titles                       ❌🐱 🖤        
├── heroes
│   └── hero                                ✅🐱    🏬     
├── icons                                   🔸🐱 🖤 🏬     
├── illustrations                           🔸🐱           
├── images
│   ├── image-cropper                       ❌🐱 🖤      ?? en suppression ?
│   └── image-with-caption                  ❌🐱         🔥 Kitten utilisé dans Karl
├── layout
│   ├── arrow-container                     ✅🐱 🖤 🏬     
│   ├── horizontal-stroke                   ✅🐱 🖤 🏬     
│   │   └── common
│   ├── icon-container                      ✅   🖤        
│   ├── line                                ❌🐱 🖤 🏬     
│   ├── marger                              ❌🐱 🖤 🏬     
│   ├── responsive-iframe-container         ❌🐱 🖤 🏬     
│   ├── separator                           ❌🐱 🖤 🏬     
│   ├── side-layout                         ❌🐱 🖤      ?? Kitten utilisé dans Karl
│   └── vertical-stroke                     ❌🐱    🏬     
├── lines
│   └── info-lines                          ✅   🖤 🏬     
├── links
│   ├── external-rich-link                  ❌🐱         !! KissKiss à supprimer de app-kitten.js
│   │                                                       Kitten utilisé dans Karl
│   └── link-list                           ❌   🖤 🏬     
├── lists
│   ├── bullet-list                         ✅🐱 🖤 🏬     
│   ├── check-list                          ✅      🏬     
│   ├── icon-list                           ✅🐱 🖤        
│   ├── list                                ✅🐱           
│   ├── nav-list                            ✅🐱         🔥 Kitten: Dropdowns/user-menu et dans Karl
│   ├── tag-list                            ❌           🔥 Kitten: ProjectCard, ProjectSimilarCard, Karl
│   └── timeline                            ✅🐱 🖤 🏬      Kitten: Karl
├── loaders
│   ├── loader                              ❌🐱 🖤 🏬     
│   └── loader-with-paragraph               ❌🐱 🖤 🏬     
├── logos
│   ├── kisskissbankbanklogo                🔸🐱 🖤 🏬     
│   └── lendopolis-logo                     🔸🐱    🏬     
├── media/embed-player.js                   🔸   🖤 🏬   !! KissKiss & Lendo à migrer vers le nouveau
├── menus
│   └── header-menu                         ✅🐱 🖤 🏬     
│       └── components/badge.js             ❌           ?? dépend de notifications/badge
├── meters
│   ├── counter-block                       ✅      🏬     
│   ├── progress                            ✅🐱 🖤 🏬     
│   └── progress-ring                       ✅🐱 🖤      ?? Kitten: Karl
├── modals
│   ├── modal                               ✅🐱 🖤 🏬   ?? Kitten: Karl
│   ├── next                                ✅   🖤 🏬     
│   └── overlay                             ✅   🖤 🏬   ?? KissKiss inutilisé
│                                                           Lendo appartient à l'ancien header
├── navigation
│   ├── header-nav                          ✅   🖤 🏬     
│   ├── horizontal-nav                      ❌   🖤 🏬   ?? KissKiss à remplacer par NavBar
│   ├── nav-bar                             ✅           ?? remplacera HorizontalNavigation et TabBar
│   ├── pagination                          ✅   🖤 🏬     
│   └── tab-bar                             ❌🐱 🖤      !! KissKiss utilisé en SCSS, à remplacer par NavBar
├── notifications
│   ├── alert.js                            ✅   🖤 🏬     
│   ├── badge.js                            ❌🐱 🖤      ?? KissKiss utilisé en CSS aussi ?
│   │                                                       Kitten utilisé dans HorizontalNav
│   └── icon-badge.js                       ❌🐱         ?? KissKiss utilisé dans ProjectCard et RewardCard
├── pages
│   └── markdown                            🔸   🖤 🏬     
├── popovers
│   ├── call-to-action-popover.js           ❌🐱         🔥 Kitten utilisé dans Karl
│   ├── popover.js                          ❌🐱         🔥 Kitten utilisé dans CallToActionPopover et Karl
│   └── simple-popover                      ✅             
├── search
│   └── search-input                        ✅   🖤        
├── simulators                              ❌           🔥 Kitten utilisé dans Karl
├── sliders
│   ├── slider-bar.js                       ❌🐱            Kitten utilisé dans form/slider, SliderWithTooltipAndPower
│   ├── slider-tooltip.js                   ❌🐱         🔥 Kitten utilisé dans SliderWithTooltipAndPower
│   └── slider-with-tooltip-and-power.js    ❌🐱    🏬   !! Lendo vérifier que la page est toujours ok
│                                                           Kitten utilisé dans LoanSimulator
├── status-with-bullet                      ✅   🖤        
├── steppers
│   ├── next
│   │   └── stepper                         ✅             
│   ├── stepper.js                          ❌🐱 🖤      ?? KissKiss Old Maker, Kitten Karl
│   ├── stepper-icon.js                     ❌   🖤      ?? KissKiss Mentor Signup
│   └── vertical-stepper                    ✅   🖤        
├── tables
│   ├── double-entry-table                  ✅   🖤        
│   ├── list-table                          ✅   🖤 🏬     
│   └── single-entry-table                  ✅   🖤        
├── text-copy                               ✅   🖤        
├── tooltips
│   ├── question-mark-with-tooltip          🔸           🔥
│   ├── static-tooltip                      ❌   🖤        
│   ├── tooltip                             ❌🐱 🖤 🏬     
│   └── tooltip-new                         ❌🐱         ?? Kitten utilisé dans le HOC `withTooltip`
│                                                           withTooltip utilisé sur Lendo dans SimulatorFormFields
├── tours
│   ├── header-tour                         ❌           🔥
│   ├── highlight-halo                      ✅   🖤        
│   ├── tour                                ❌🐱         🔥 Kitten utilisé dans tours/header-tour
│   ├── tour-popover                        ❌🐱         🔥 Kitten utilisé dans tours/header-tour
│   └── tour-step                           ❌🐱         🔥 Kitten utilisé dans tours/header-tour
├── typography
│   ├── paragraph                           ❌🐱 🖤 🏬     
│   │   └── next                            ✅      🏬     
│   ├── sup-title                           ❌           🔥
│   ├── text                                ❌🐱 🖤 🏬     
│   ├── title                               ✅🐱 🖤 🏬     
│   └── title-with-stroke                   ✅🐱 🖤 🏬     
├── uploaders
│   ├── basic-uploader                      ✅🐱 🖤 🏬   ?? Kitten utilisé dans images/image-cropper
│   ├── document-manager                    ✅   🖤        
│   ├── simple-uploader                     ❌      🏬   ?? Lendo voir si toujours en suppression
│   └── uploader                            ❌🐱           
└── videos
    ├── embed-player                        ✅             
    ├── gif-video                           ✅🐱 🖤        
    └── video                               ✅   🖤        
```

**Comment by joachimesque** [comment]
## Composants à supprimer :

- [ ] `buttons/button-image-with-text`
- [ ] `buttons/button-image-with-text-and-badge`
- [ ] `cards/article-card`
- [ ] `cards/contribution-card`
- [ ] `cards/project-card`
- [ ] `cards/project-creator-card`
- [ ] `cards/project-similar-card`
- [ ] `cards/reward-card/legacy`
- [ ] `cards/similar-projects-card`
- [ ] `carousel/tab-bar-carousel`
- [ ] `dropdowns/dropdown`
- [ ] `dropdowns/dropdown-button`
- [ ] `dropdowns/phone-dropdown`
- [ ] `dropdowns/user-menu`
- [ ] `form/form-amount-and-currency` (à vérifier)
- [ ] `form/form-row`
- [ ] `form/search`
- [ ] `form/select-with-state` (une fois DropdownSelect poussé)
- [ ] `form/slider`
- [ ] `grid/lego-grid`
- [ ] `images/image-with-caption`
- [ ] `links/external-rich-link`
- [ ] `lists/nav-list`
- [ ] `lists/tag-list`
- [ ] `popovers/call-to-action-popover.js`
- [ ] `popovers/popover.js`
- [ ] `simulators`
- [ ] `sliders/slider-bar.js`
- [ ] `sliders/slider-tooltip.js`
- [ ] `sliders/slider-wit-tooltip-and-power.js`
- [ ] `tooltips/question-mark-with-tooltip`
- [ ] `uploaders/simple-uploader`
- [ ] `uploaders/uploader`

## Composants à convertir

- [ ] `avatar/avatar-with-text-and-badge`
- [ ] `box/information-box`
- [ ] `buttons/button-icon`
- [ ] `buttons/button-image`
- [ ] `buttons/button-question-mark-icon`
- [ ] `buttons/close-button`
- [ ] `buttons/social-button-icon`
- [ ] `buttons/social-button-icon-words`
- [ ] `cards/simple-card`
- [ ] `dev`
- [ ] `dropdowns/v2`
- [ ] `form/form-actions`
- [ ] `form/label`
- [ ] `form/location-input`
- [ ] `form/switch` (voir la différence avec form/toggle-switch)
- [ ] `form/text-input-and-select` (à vérifier)
- [ ] `grid/grid`
- [ ] `grid/row` (utilité à confirmer)
- [ ] `grid/side-grid` (utilité à confirmer)
- [ ] `images/image-cropper`
- [ ] `layout/line`
- [ ] `layout/marger`
- [ ] `layout/responsive-iframe-container`
- [ ] `layout/separator`
- [ ] `layout/side-layout` (utilité à confirmer)
- [ ] `layout/vertical-stroke`
- [ ] `links/link-list`
- [ ] `loaders/loader`
- [ ] `loaders/loader-with-paragraph`
- [ ] `menus/header-menu/components/badge.js` (inspection minutieuse à effectuer sur l'utilisation)
- [ ] `notifications/badge.js`
- [ ] `notifications/icon-badge.js`
- [ ] `steppers/stepper.js`
- [ ] `steppers/stepper-icon`
- [ ] `tooltip/static-tooltip`
- [ ] `tooltip/tooltip`
- [ ] `tooltip/tooltip-new`
- [ ] `tours/header-tour`
- [ ] `tours/tour`
- [ ] `tours/tour-popover`
- [ ] `tours/tour-step`
- [ ] `typography/sup-title`
- [ ] `typography/text`


## Composants dépréciés à migrer :

### KissKiss

- [ ] `box/link-box/link-box/deprecated.js`
- [ ] `buttons/button`
- [ ] `comments/comment` && `form/comment`
- [ ] `comments/comment-form` && `form/comment-form`
- [ ] `headers/header`
- [ ] `headers/header-logo`
- [ ] `headers/header-titles`
- [ ] `navigation/horizontal-nav`
- [ ] `navigation/tab-bar`
- [ ] `notifications/badge.js`
- [ ] `typography/paragraph`

### Lendo

- [ ] `buttons/button`
- [ ] `headers/header`
- [ ] `headers/header-logo`
- [ ] `navigation/horizontal-nav`
- [ ] `navigation/tab-bar`
- [ ] `typography/paragraph`

**Comment by joachimesque** [comment]
## Composants à convertir

- [ ] `avatar/avatar-with-text-and-badge`
- [ ] `box/information-box`
- [ ] `buttons/button-icon`
- [ ] `buttons/button-image`
- [ ] `buttons/button-question-mark-icon`
- [ ] `buttons/close-button`
- [ ] `buttons/social-button-icon`
- [ ] `buttons/social-button-icon-words`
- [ ] `cards/simple-card`
- [ ] `dev`
- [ ] `dropdowns/v2`
- [ ] `form/form-actions`
- [ ] `form/label`
- [ ] `form/location-input`
- [ ] `form/switch` (voir la différence avec form/toggle-switch)
- [ ] `form/text-input-and-select` (à vérifier)
- [ ] `grid/grid`
- [ ] `grid/row` (utilité à confirmer)
- [ ] `grid/side-grid` (utilité à confirmer)
- [ ] `images/image-cropper`
- [ ] `layout/line`
- [ ] `layout/marger`
- [ ] `layout/responsive-iframe-container`
- [ ] `layout/separator`
- [ ] `layout/side-layout` (utilité à confirmer)
- [ ] `layout/vertical-stroke`
- [ ] `links/link-list`
- [ ] `loaders/loader`
- [ ] `loaders/loader-with-paragraph`
- [ ] `menus/header-menu/components/badge.js` (inspection minutieuse à effectuer sur l'utilisation)
- [ ] `notifications/badge.js`
- [ ] `notifications/icon-badge.js`
- [ ] `steppers/stepper.js`
- [ ] `steppers/stepper-icon`
- [ ] `tooltip/static-tooltip`
- [ ] `tooltip/tooltip`
- [ ] `tooltip/tooltip-new`
- [ ] `tours/header-tour`
- [ ] `tours/tour`
- [ ] `tours/tour-popover`
- [ ] `tours/tour-step`
- [ ] `typography/sup-title`
- [ ] `typography/text`

**Comment by FlorentD** [comment]
Petite liste de nos dépendances principales actuelles : 
- En gras, il faudra faire un effort pour mettre à jour (BREAKING CHANGE)
- ✅ => On garde la dépendance
- :x: => On se sépare de la dépendance
- Quand c'est coché on considère que les actions sur la lib est faite

- [ ] downshift                                      6.0.6  →     6.1.0 ✅
- [ ]  html-to-react                                  1.4.3  →     1.4.5
- [ ]  **js-base64                                      2.5.2  →     3.6.0**
- [ ]  lodash                                       4.17.19  →   4.17.20
- [ ]  pubsub-js                                      1.8.0  →     1.9.2
- [ ]  react-cropper                                  2.1.1  →     2.1.6
- [ ]  **react-dropzone                                3.13.1  →    11.3.1**
- [ ]  **react-markdown                                 2.5.1  →     5.0.3**
- [ ]  react-modal                                   3.11.2  →    3.12.1
- [ ]  react-number-format                            4.4.1  →     4.4.4
- [ ]  **react-places-autocomplete                      5.4.3  →     7.3.0**
- [ ]  **react-select                                   1.0.0  →     4.1.0**
- [ ]  **react-tooltip                                 3.11.1  →    4.2.14** :x:
- [ ]  slugify                                        1.4.5  →     1.4.6
