### ISSUE TITLE
Update styleguide for a new styleguide.

### ISSUE THREAD

**Issue by camilledel** [KissKissBankBank/kitten#564]
Fait : 
- [x] Contenus réalistes (photos vides) => #555 
- [x] Mise en place de la grille sur chaque composants => #550, #560
- [x] Redesign sous-titre et border-bottom => #553
- [x] Supprimer les props `children` dans les exemples `karl`. 
- [x] Retirer les composants avec les labels `error` sur les composants concernés ( `Form-info`, `Text-input`, ... )  =>#576
- [x] Mise à jour des colors sur Brand =>#572
- [x] Retirer toutes les double quotes.
- [x] Menu : Revoir l'organisation des catégories pour en avoir moins à l'ouverture du menu.
- [x] Revoir les catégories de composants et l'ordre des catégories #609
- [x] A voir si l'on cache certains composants
- [x] Revoir les composants cassés ( Dropdown, ... )
- [x] Changement ou oubli de certains styles sur ( `Form-amount-and-currency`, `Form-phone-number`, `Select`) sur le `disabled`
- [x] Revoir certains noms de composants
- [x] Revoir `simulator` component.

En cours :
- [x] Revoir le header => #578
- [x] Menu : Revoir le style pour facilité la distinction entre  `Brand colors` et `Component` => #620 
- [x] Menu : Fermeture dès le click sur un sous-élément. 
- [x] Menu : Faire passer le menu par-dessus et opacité sur le contenu quand il est ouvert

À faire : 
- [ ] `TagButton` (état normal en rollOver, `valid` et `error` sans rollOver)
- [ ] `TextInputWithUnit`

Plus tard :
- [ ] Ajouter une page `About`

**Comment by solenema** [comment]
1/ Ordre et organisation des composants

 [Voici l'ordre retenu pour l'organisation des composants](https://docs.google.com/document/d/1ds22b1_jnRkHXTuo4yRAeEw3RAfxEqzuLYdfkboFz-8/edit#  )avec tous les composants qui sont présents sur 'master' à date.

à noter que certaines catégories ont été supprimées, et les composants de ces catégories ont été répartis dans d'autres catégories. 

- Lists
- Headers
- Popovers
- Steppers
- Box
....

Voici donc les catégories retenues:

- Grid System
- Typography
- Navigation
- Buttons
- Form elements
- Crowdfunding
- Notifications
- Contextual content
- Presentation elements

=> à tous les kitten people, il faut maintenant suivre cette catégorisation pour les nouveaux composants, on pourra bien sûr en ajouter à l'avenir.

**2/ Cas des Dropdowns**

J'aimerais discuter des composants "dropdowns", car je ne comprends pas pourquoi on les sépare du user menu et du platform switch. Pour l'instant l'un (dropdown) n'existe pas sans l'autre (user menu ou platform switch) donc je trouve que les séparer complexifie la compréhension du composant. 

**3/ Todos spottées au passage**

- [ ] “Button heart icon words” => à renommer “Button with icon and words”
- [ ]  “Payment button” => ne pas mettre 2 fois Visa mais Visa + Mastercard
- [ ] "Card" => Il faut rendre cela plus digeste en réduisant leur taille pour se rapprocher de la façon dont on les utilise sur les sites, il faut aussi valider les couleurs avec Kévin. 
- [ ] "Form phone number" => trouver une solution pour que quand je sélectionne "+33 (FR)", le texte ne se coupe pas, soit on peut facilement n'afficher que "+33" soit il faut revoir l'UI avec Kévin.
- [ ] "Select" et "Slider" => revoir la largeur de ces composants pour se rapprocher de la réalité, voir avec Kévin. 
- [ ] Liens "Toggle fixed version" : peut-on utiliser le style des "link" de kitten, là j'ai une couleur chelou.
- [ ]  "Hero" => il faut le rendre plus compréhensible, à travailler ensemble
- [ ]  "Tab bar with React components" => ne garder que le composant react et les mettre dans "tab bar" et "tab bar with 4 items
- [ ] Toujours ajouter un sous-sous-titre, quite à répéter le nom du sous-titre, par exemple "Press Quotes" n'en a pas.
- [ ] Loan Simulators : si possible réduire la largeur, ou mieux, les mettre dans une card comme sur hellomerci 
- [ ] "Titre avec deux boutons" => renommer en anglais "Title with two buttons"

**4/ Composants à cacher si possible**
Mais ce ne sera pas bloquant pour une v1.
- "Simulator result" : on pourrait même le supprimer car il n'est plus utilisé
- "External rich link"

@camilledel  @Ynote @sunny voilà !

Pour les prios : l'organisation #1 / le menu #2 / Et on verra ensuite pour les tâches que j'ai ajoutées ici.

**Comment by solenema** [comment]
Suite à la réu Kit UI du 5 avril, il a été décidé que:

1/ tous les composants qui ne sont pas utiles à la compréhension de l'interface d'un point de vue produit mais qui sont utiles pour le développement d'un composant, par exemple le "Expand me" de la dropdown seront ajoutés dans une catégorie "Développeur" (à voir si on la nomme comme ça)

2/ On supprime bien la catégorie "Dropdowns" et on complète le "user-menu" et le "platform-switch" pour avoir un composant fonctionnel complet.
