### ISSUE TITLE
Last todo Styleguide v1

### ISSUE THREAD

**Issue by solenema** [KissKissBankBank/kitten#647]
- [x] Nom des couleurs, placer l'adjectif devant le nom. Exemple : changer "grey semi light" pour "Semi light grey"
- [x] Title : mettre en exemple un titre d'au moins 4 mots. Exemple "Lorem ipsum dolor sit amet"
- [x] Checkbox : remplacer "Filter 1" et "Filter 3" par "Item 1" et "Item 2" plus générique
- [x] Select : Remplacer "Taxonomia" par "Select"
- [x] Search input : Remplacer "Rechercher" par "Search"
- [x] Form row : Remplacer "Lorem ipsum..." par "Button"
- [x] Form info : remplacer "Label name here" par "Label name" partout 
- [x] Tour : remplacer le titre "Nouveautés" par "What's new" et le paragraphe par du Lorem Ipsum .., remplacer "SUIV" par "NEXT" et PREC par "BACK"
- [x] Remplacer "Reimbursing" par"'I'd like to reimburse" et "comission" par "fees"
- [x] Popover : remplacer par du lorem ipsum qui bouge, là c'est toujours la même phrase, on s'ennuie un peu. Et remplacer "Découvrir" par "ACTION"
- [x] Testimony : remplacer les textes en anglais par du Lorem ipsum
- [x] Title with actions : remplacer le texte dans les boutons par "ACTION 1 TITLE" "ACTION 2 TITLE"
- [x]  Form row est à deux endroits, peut on le garder uniquement dans "Layout" et le supprimer de "FORM ELEMENTS"
- [x] Les payment buttons se chevauchent :  https://www.dropbox.com/s/9viv7cmcx7o8wqv/Screenshot%202017-05-11%2014.04.05.png?dl=0
