### ISSUE TITLE
[Styleguide] Réparer les composants non responsive et cassés

### ISSUE THREAD

**Issue by camilledel** [KissKissBankBank/kitten#817]
Checker et réparer les composants qui ne s'adaptent pas en responsive et cassé.

- [x] PhoneIllustration (background noir) #827
- [ ] SearchInput ( retirer le `appearance: none)
- [ ] TagList Pourquoi 2 `ul` identique
![capture d ecran 2017-09-08 a 18 29 31](https://user-images.githubusercontent.com/11648042/30221517-da49a72a-94c3-11e7-929f-e3f8fa2cce13.png)

- [x] Revoir la présentation de `loader` #828
- [x] Border de couleurs différentes (LinkBox / InformationBox) #833
