### ISSUE TITLE
Bug - `line-height` écrasé dans le composant `Text`

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#865]
En utilisant le composant comme suit, le line-height souhaité est `normal`, hors j'obtiens le line-height ajouté via la prop `size` qui ajoute `font-size: …; line-height: 1.5;`.

**Objectif** : Il faudrait trouver une solution pour que la prop `lineHeight` prenne le dessus sur les autres (`!important` ou autre solution).

```js
<Text size="micro" color="error" lineHeight="normal">
  Veuillez déposer un document au format .pdf, .jpg, .jpeg, .gif
  et .png <br />dont la taille ne dépasse pas 7mo.
</Text>
```

<img width="199" alt="capture d ecran 2017-10-20 a 13 51 11" src="https://user-images.githubusercontent.com/736319/31819745-47b2193c-b59e-11e7-9b1f-3e45bf28319d.png">

## TODO

- [ ] `.k-u-size-` ne gèrent que l'attribut `font-size`
- [ ] Ajout de `k-u-color-valid` et compréhension dans `<Text />`
- [ ] Fixer le problème de la prop `style` qui écrase celle par défaut

**Comment by LanF3usT** [comment]
Dans une logique d'une classe utilitaire pour un attribut, j'ai l'impression qu'une bonne solution serait que les classes `.k-u-size-…` ne gère que l'attribut `font-size`. Ca réglerait le problème et serait en adéquation avec la logique citée plus haut.

**Comment by Ynote** [comment]
Je suis d'accord. La logique des classes utilitaires ne peut fonctionner dans notre système de composants que si on associe une seule déclaration CSS à une classe. 

En vrai, ce sont même les seules classes où on pourrait avoir l'usage de `!important` si on voulait que ces déclarations soient immutables.

**Comment by LanF3usT** [comment]
Il faudrait qu'on en profite pour ajouter `k-u-color-valid` et l'ajouter dans `<Text color="valid" />`.

**Comment by LanF3usT** [comment]
Il y a un problème également sur `<Text />` qui accepte la prop `style`. Ca nous empêche d'ajouter des styles au composant. On pourrait la renommer `fontStyle`, un truc du `style`.
