### ISSUE TITLE
Semaine du 23 au 27 octobre

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#873]
# TODO

## Camille

- [x] Update des fonts => https://github.com/KissKissBankBank/kitten/pull/860
- [x] Update des colors => https://github.com/KissKissBankBank/kitten/pull/853
- [x] Update `Title` and `Paragraph` => https://github.com/KissKissBankBank/kitten/pull/863
- [x] Update `TextInputWithButton` => https://github.com/KissKissBankBank/kitten/pull/867
- [x] Update `Alert` component => https://github.com/KissKissBankBank/kitten/pull/869
- [x] Update `Form elements` => https://github.com/KissKissBankBank/kitten/pull/872
- [ ] Update `karl-Title` and `karl-Section__title` class => https://github.com/KissKissBankBank/kitten/pull/868
- [ ] Update `Button` and `ButtonIcon` => https://github.com/KissKissBankBank/kitten/pull/866 (voir pour le btn 'Beryllium`)

## Bastien

- [x] Étudier le merge dans `master` de https://github.com/KissKissBankBank/kitten/pull/860
- [x] Faire tourner les nouvelles fonts sur les KissKiss et LENDO.
- [x] Mise à jour de `Text` => https://github.com/KissKissBankBank/kitten/issues/865
