### ISSUE TITLE
Semaine du 30 octobre au 3 novembre

### ISSUE THREAD

**Issue by camilledel** [KissKissBankBank/kitten#880]
# TODO

## Camille

Mergé dans `add-new-font`
- [x] Update `Button` and `ButtonIcon` => https://github.com/KissKissBankBank/kitten/pull/866 (voir pour le btn 'Beryllium`)
- [x] Update `TagList` => https://github.com/KissKissBankBank/kitten/pull/884
- [x] Update `RadioButton` and `Checbox` =>https://github.com/KissKissBankBank/kitten/pull/872
- [x] Update  `Title` and `Paragraph` => https://github.com/KissKissBankBank/kitten/pull/863
- [x] Update `TextInput` … => https://github.com/KissKissBankBank/kitten/pull/867
- [x] Update `Alert` => https://github.com/KissKissBankBank/kitten/pull/869
- [x] Update `Tooltip` and `StaticTooltip` => https://github.com/KissKissBankBank/kitten/pull/882
- [x] `ProjectCard` => https://github.com/KissKissBankBank/kitten/pull/883

## En attente de review
- [x] Update `HorizontalNav` => https://github.com/KissKissBankBank/kitten/pull/888
- [x] Update `Label` and `FormInfo` => https://github.com/KissKissBankBank/kitten/pull/887
- [x] Update `TagButton` and `PaymentButton` => https://github.com/KissKissBankBank/kitten/pull/886
- [x] Update `Stepper` => https://github.com/KissKissBankBank/kitten/pull/885
- [x] Update `Select` => https://github.com/KissKissBankBank/kitten/pull/881
- [x] Update `Tour` => https://github.com/KissKissBankBank/kitten/pull/879
- [x] Update `UserMenu` => https://github.com/KissKissBankBank/kitten/pull/898
- [x] Update `TabBar` => https://github.com/KissKissBankBank/kitten/pull/891
- [x] Update `karl-Title` and `karl-Section__title` class => https://github.com/KissKissBankBank/kitten/pull/868

## A checker avec le produit 
- [x] Update `TabBar` => https://github.com/KissKissBankBank/kitten/pull/891
## Autres
- [x] Double `font-weight` `body` class.
- [x] Rédiger l'annonce pour freelance
- [ ] Créer le `ButtonIcon` instagram
- [ ] Chercher boite pour magnets (magnet UX)

## Bastien
- [x] Review en pair programming
- [x] Tester la nouvelle font avec toutes les PR qui fixent la graisse.
- [ ] Rédiger l'annonce pour freelance
