### ISSUE TITLE
Semaine du 13 au 17 novembre

### ISSUE THREAD

**Issue by camilledel** [KissKissBankBank/kitten#920]
# TODO

## Camille
- [ ] Contacter freelance (création du compte sur Malt)
- [x] Créer le `ButtonIcon` instagram
- [ ] Chercher boite pour magnets (magnet UX)
- [ ] Anti-aliasing
- [x] Checker les composant sur KissKiss. Cleaner l'ancienne font
- [ ] Commencer à rédiger le guidelines

## Bastien

- [ ] Mettre en ligne les fonts sur KKBB et LENDO ?
- [ ] Rédiger les annonces sur diverses plateformes
- [ ] Prendre contact avec des freelances
