### ISSUE TITLE
Semaine du 20 au 25 novembre

### ISSUE THREAD

**Issue by camilledel** [KissKissBankBank/kitten#937]
# TODO

## Camille
- [x] Mise à jour tous les buttons
- [ ] MAJ Forms
- [ ] MAJ horizontalNav
- [x] Integrer `ButtonIcon` instagram
- [x] Contacter freelance
- [ ] Chercher boite pour magnets (magnet UX)
- [x] Anti-aliasing
- [ ] Commencer à rédiger le guidelines
- [x] Lien issue Solène

## Bastien

- [x] Mettre en ligne les fonts sur KKBB et LENDO ?
- [x] Rédiger les annonces sur diverses plateformes
- [x] Prendre contact avec des freelances
