### ISSUE TITLE
Semaine du 27 novembre au 1er décembre

### ISSUE THREAD

**Issue by camilledel** [KissKissBankBank/kitten#964]
# TODO

## Camille
- [ ] Composant `petit trait`
- [ ] Revoir le nom du composants `StrokeSmall` (<div> en display: block)
- [ ] Footer
- [ ] Chercher boite pour magnets (magnet UX)
- [ ] Commencer à rédiger le guidelines

## Bastien
